
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.practica1.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREEN = 15;
  public static final int SQUARE = 5;
  public static final int PLUS = 27;
  public static final int RECTA = 6;
  public static final int CURVE = 9;
  public static final int DECIMAL = 23;
  public static final int SLASH = 29;
  public static final int BLACK = 17;
  public static final int PINK = 19;
  public static final int CIRCLE = 4;
  public static final int CLPAR = 25;
  public static final int OPPAR = 24;
  public static final int BLUE = 13;
  public static final int ID = 21;
  public static final int RED = 12;
  public static final int NUM = 22;
  public static final int OBJECT = 10;
  public static final int COMMA = 30;
  public static final int EOF = 0;
  public static final int BEFORE = 11;
  public static final int POLY = 7;
  public static final int BROWN = 16;
  public static final int ASTER = 28;
  public static final int GRAPH = 2;
  public static final int error = 1;
  public static final int LINE = 8;
  public static final int YELLOW = 14;
  public static final int DASH = 26;
  public static final int ANIME = 3;
  public static final int WHITE = 18;
  public static final int PURPLE = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAPH",
  "ANIME",
  "CIRCLE",
  "SQUARE",
  "RECTA",
  "POLY",
  "LINE",
  "CURVE",
  "OBJECT",
  "BEFORE",
  "RED",
  "BLUE",
  "YELLOW",
  "GREEN",
  "BROWN",
  "BLACK",
  "WHITE",
  "PINK",
  "PURPLE",
  "ID",
  "NUM",
  "DECIMAL",
  "OPPAR",
  "CLPAR",
  "DASH",
  "PLUS",
  "ASTER",
  "SLASH",
  "COMMA"
  };
}

